config/routes.rb
Rails.application.routes.draw do

  # 1 homes
  root to: 'homes#top'
  get "/support" => "homes#support", as: 'support'

  devise_for :users
  # 2 users
  # 7 comments newのviewは要らなければ消す。
  resources :users, only: [:edit,:index, :update, :destroy] do
    resources :comments, only: [:show, :create, :destroy]
  end
  get "user/mypage" => "users#mypage", as: 'mypage'
  get 'user/unsubscribe' => "users#unsubscribe", as: 'unsubscribe'
  get 'user/:id' => "users#others", as: 'others'
  patch 'user/withdrawal' => 'users#withdrawal', as: 'withdrawal'
  # 3 colenders
  resources :calenders, only: [:show, :create, :update, :destroy]
  # 4 lists 7/2編集 create追加
  resources :lists, only: [:create, :destroy, :index]
  # 5 tags newのviewは要らなければ消す。
  resources :tags, only: [:new, :create, :destroy]
  # 6 likes
  resources :likes, only: [:create, :destroy]

  # 8 memos
  resources :memos, only: [:show, :create, :update, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calender.rb
class Calender < ApplicationRecord
  has_many :lists ,dependent: :destroy
  has_many :tags ,dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
end

app/models/list.rb
class List < ApplicationRecord

  belongs_to :user

  has_many :list_categories ,dependent: :destroy
  # 7/2 中間テーブル(list_caetegories)を通してtagsと関連付ける。
  # この記述でList.tagsの取得が可能。
  has_many :tags, through: :list_categories

  # 買い物リスト:0、要件リスト:1、日常リスト:2
  enum default_list_name: { buy: 0, work: 1, everyday: 2 }

end

app/models/list_category.rb
class ListCategory < ApplicationRecord

  belongs_to :list
  # 7/2 変更のち確認 複数のタグに所有されるのでbelongs_to
  belongs_to :tag

  validates :list_id, presence: true
  validates :tag_id, presence: true

end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :list_categories, dependent: :destroy
  has_many :lists, through: :list_categories
# optional: true で外部キーのnilを許可
  belongs_to :colender, optional: true

  validates :tag_name, presence: true
  # 変数を定義-タグの登録個数制限
  validate :check_number_of_tags

  def check_number_of_tags
    if Tag.count > 10
      errors.add(:list_category, '登録できる個数は10個までです。')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :likes ,dependent: :destroy
  has_many :comments ,dependent: :destroy
  has_many :memos ,dependent: :destroy
  has_many :lists ,dependent: :destroy

  validates :name, presence: true
  validates :encrypted_password, presence: true
  validates :email, presence: true

  # refile-画像投稿機能、画像を入れたいカラム名+id
  attachment :image

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def support
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
  end

  def create
  end

  def destroy
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def new
    @tags = Tag.all
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
     redirect_to new_tag_path, notice: "You have created tag successfully."
    else
     @ltags = Tag.all
     render :new, notice: "miss"
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to new_tag_path
  end

  private
  def tag_params
    params.require(:tag).permit(:tag_name)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def mypage
    @lists = List.all
    @user = current_user
  end

# 退会アクション
  def unsubscribe
    @user = current_user
    # unsubscribeをtrueに変更-削除
    @user.update(unsubscribe: true)
    reset_session
    redirect_to root_path, notice: '退会処理を実行致しました'
  end

# 退会後、ステータスを更新
  def withdrawal
  end

# ユーザー情報編集
  def edit
    @user = current_user
  end

# ユーザー情報更新
  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to mypage_path, notice: "更新されました"
    else
      render :edit
    end
  end

# 外部ユーザー一覧
  def index
    @users = User.all
  end

# 外部ユーザー閲覧
  def others
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calenders_helper.rb
module CalendersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h3>会員情報編集</h3>

<% if @user.errors.any? %>
 <ul>
  <h6>
    <%= @user.errors.count %> error prohibited this obj from being updateed:
  </h6>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
 </ul>
<% end %>


<%= form_with model: @user, url: user_path(@user.id), method: :patch do |f| %>
 <p>
   <%= f.label "名前" %>
   <%= f.text_field :name, id:"inputName" %>
 </p>
 <p>
   <%= f.attachment_field :image %>
 </p>
 <p>
   <%= f.label "自己紹介" %>
   <%= f.text_field :introduction %>
 </p>
 <p>
   <%= f.submit "編集内容を保存" %>
   <%= link_to "退会する", unsubscribe_path %>
 </p>
<% end %>

app/views/users/index.html.erb
   <h2>Users</h2>
   <table class="table">
     <thead>
       <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
       </tr>
     </thead>
     <tbody>
       <% @users.each do |users| %>
       <tr>
        <td><%=%></td>
        <td><%= users.name %></td>
        <td><%= link_to "Show", others_path(users.id) %></td>
       </tr>
       <% end %>
     </tbody>
    </table>

app/views/users/mypage.html.erb
<h1>mypage</h1>
<!--プロフィール画像-->
<p>
  <% if @user.image_id.present? %>
   <%= image_tag attachment_url(@user, :image, format: "png"), class: 'plofileimage pt-15', style: 'max-height: 150px width: 100%' %>
  <% else %>
   <%= image_tag 'test1.png', class: 'plofileimage pt-15', style: 'max-height: 150px width: 100%' %>
  <% end %>
</p>
<!--カレンダー-->
<%= month_calendar do |date| %>
  <%= date.day %>
<% end %>


<!--list 一覧-->
<span>リスト一覧</span>
<ul>
<li>買い物リスト<%= link_to 'リストにタグ+', new_tag_path %>
  <ul>
  <li>タグ</li>
  <li>タグ</li>
  <li>タグ</li>
  </ul>
</li>
<li>要件リスト
  <ul>
  <li></li>
  <li></li>
  <li></li>
  </ul>
</li>
<li>日常リスト
  <ul>
  <li></li>
  <li></li>
  <li></li>
  </ul>
</li>
</ul>

<div class="memo">
</div>

<%= link_to 'リストを追加', lists_path %>
<%= link_to 'リストにタグを追加', new_tag_path %>
<%= link_to 'ユーザー情報の編集', edit_user_path(@user.id) %>

app/views/users/others.html.erb
<!--閲覧のみにする-->

<h3>Show</h3>
<p>保持しているデータの表示</br>
   - カレンダー
   - タグ
   - 予定の表示のみ
</p>

app/views/users/template.html.erb
<!--mypage用 部分テンプレート-->

<!--listとtagの投稿-->

app/views/users/unsubscribe.html.erb
<!--PATH: unsubscribe_path-->

    <h5><strong>本当に退会しますか？</strong></h5>
    <p>
     退会すると、会員登録情報や</br>
     これまでの購入履歴が閲覧できなくなります。</br>
     退会する場合は、「退会する」をクリックしてください。</br>
    </p>
    <p>
     <%= link_to "退会しない", mypage_path %>
     <%= link_to "退会する", withdrawal_path, method: :patch, data: {confirm: "本当に退会しますか？"} %>
    </p>