config/routes.rb
Rails.application.routes.draw do

  # 1 homes
  root to: 'homes#top'
  get "/support" => "homes#support", as: 'support'

  devise_for :users
  # 2 users
  # 7 comments newのviewは要らなければ消す。
  resources :users, only: [:edit,:index, :update, :destroy] do
    resources :comments, only: [:show, :create, :destroy]
  end
  get "user/mypage" => "users#mypage", as: 'mypage'
  get 'user/unsubscribe' => "users#unsubscribe", as: 'unsubscribe'
  get 'user/:id' => "users#others", as: 'others'
  patch 'user/withdrawal' => 'users#withdrawal', as: 'withdrawal'
  # 3 colenders
  resources :calenders, only: [:show, :create, :update, :destroy]
  # 4 lists 7/2編集 create追加
  resources :lists, only: [:create, :destroy, :index]
  # 5 tags newのviewは要らなければ消す。
  resources :tags, only: [:new, :create, :destroy]
  # 6 likes
  resources :likes, only: [:create, :destroy]

  # 8 memos
  resources :memos, only: [:show, :create, :update, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calender.rb
class Calender < ApplicationRecord
  has_many :lists ,dependent: :destroy
  has_many :tags ,dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
end

app/models/list.rb
class List < ApplicationRecord

  belongs_to :user

  has_many :list_categories ,dependent: :destroy
  # 7/2 中間テーブル(list_caetegories)を通してtagsと関連付ける。
  # この記述でList.tagsの取得が可能。
  has_many :tags, through: :list_categories

  # 買い物リスト:0、要件リスト:1、日常リスト:2
  enum default_list_name: { buy: 0, work: 1, everyday: 2 }

end

app/models/list_category.rb
class ListCategory < ApplicationRecord

  belongs_to :list
  # 7/2 変更のち確認 複数のタグに所有されるのでbelongs_to
  belongs_to :tag

  validates :list_id, presence: true
  validates :tag_id, presence: true

end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :list_categories, dependent: :destroy
  has_many :lists, through: :list_categories
# optional: true で外部キーのnilを許可
  belongs_to :colender, optional: true

  validates :tag_name, presence: true
  # 変数を定義-タグの登録個数制限
  validate :check_number_of_tags

  def check_number_of_tags
    if Tag.count > 10
      errors.add(:list_category, '登録できる個数は10個までです。')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :likes ,dependent: :destroy
  has_many :comments ,dependent: :destroy
  has_many :memos ,dependent: :destroy
  has_many :lists ,dependent: :destroy

  validates :name, presence: true
  validates :encrypted_password, presence: true
  validates :email, presence: true

  # refile-画像投稿機能、画像を入れたいカラム名+id
  attachment :image

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def support
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def new
    @tags = Tag.all
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
     redirect_to new_tag_path, notice: "You have created tag successfully."
    else
     @ltags = Tag.all
     render :new, notice: "miss"
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to new_tag_path
  end

  private
  def tag_params
    params.require(:tag).permit(:tag_name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calenders_helper.rb
module CalendersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZuboraTask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<!--6/30 stylesheet link → pack に変更 -->
    <!--CDNを使用する場合は、この下にscriptタグを挿入する。前頁共通のものはこれ-->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
        <div class="container">
          <div>
            <% if user_signed_in? %>
            <div class="align-center">
             <%= current_user.name %> さんのタスク管理
            </div>
            <ul class="navbar-nav">
             <li class="nav-item">
              <%= link_to 'マイページ', mypage_path %>
             </li>
             <li class="nav-item">
              <%= link_to 'サポート', support_path %>
             </li>
             <li class="nav-item">
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
             </li>
            <% else %>
             <li class="nav-item">
              <%= link_to '新規登録', new_user_registration_path %>
             </li>
             <li class="nav-item">
              <%= link_to 'ログイン', new_user_session_path %>
             </li>
            <% end %>
            </ul>
         </div>
       </div>
      </nav>

      <div class="icon">
         <!--user一覧-->
         <p><%= link_to 'ほかのユーザー一覧', users_path %></p>
         <!--user編集画面-->
      </div>

    </header>

    <main>
      <% if flash[:notice] %>
       <p id = "notice"><%= flash[:notice] %></p>
      <% end %>
      <%= yield %>
    </main>

    <footer>

    </footer>
  </body>
</html>